### ISSUE TITLE
identities can be assumed

### ISSUE THREAD

**Issue by rmbryan71** [MartinSnyder/haskell-mud#3]
If one player selects a name, then a second player enters and chooses the same name, they are allowed to do so. I'm not entirely sure what happens after that. It looks like there's only one character, but it responds to both windows.

**Comment by MartinSnyder** [comment]
This is intentional at this point. The server is connection less, so anyone presenting a name with their command will execute as that user.

The answer would be to add accounts and a security model, which are not part of the plan currently.
