### ISSUE TITLE
feature request: World reset secret

### ISSUE THREAD

**Issue by rmbryan71** [MartinSnyder/haskell-mud#4]
Just for testing, I would like to have some way to reset the world on command.

**Comment by MartinSnyder** [comment]
The best way to accomplish this is to run the game locally. You would need to:
1. Install stack (https://docs.haskellstack.org/en/stable/README/) locally, 
2. Clone the repository
3. Run "stack ghci" from command line
4. type ":main 8080" or ":main console"

If you are on Windows, use WSL/ubuntu and install the ubuntu version of stack.
